### ISSUE TITLE
Set up CI/CD pipeline

### ISSUE THREAD

**Issue by dstockhammer** [zalando-incubator/clin#4]
# One-line summary
Set up CI/CD pipeline to build, test and publish to PyPI

## Description
Set up a pipeline that builds and tests all pull requests. When a release is created, the app is packaged and pushed to PyPI: https://pypi.org/project/clin

## Open Questions:
- How to do versioning?
- How to create releases?

## Types of Changes
- Documentation / non-code

## Tasks
- [x] Build and test on master and on pull requests
- [x] Decide on a versioning strategy and implement creating releases
- [x] Decide on a linter and add it to the pipeline. I propose [black](https://github.com/psf/black)
- [x] Push releases to PyPI

**Comment by Dmitry-Erokhin** [comment]
I think this can be closed now
